### ISSUE TITLE
ledmatrixctl depends on library that requires licence key

### ISSUE THREAD

**Issue by sde1000** [FrameworkComputer/inputmodule-rs#105]
When running ledmatrixctl, I see the following popup window:
![image](https://github.com/FrameworkComputer/inputmodule-rs/assets/815708/9a42addd-9f0a-4026-a67d-d02c600dc7bf)

If I click "Cancel", I can't continue — the program just exits, even if I'm trying to use it in command-line mode.

(I'm not willing to accept this licence. Further discussion: https://discuss.python.org/t/pysimplegui-now-requires-a-paid-license-opinions/48790 )

**Comment by ratijas** [comment]
Moreover, the package for python-pysimplegui on Arch Linux fails to even build from AUR, because apparently they've also retroactively nuked existing pre-built packages. But the more I read about the project on that linked forum, the more I'm glad I couldn't run it on my machine.

**Comment by TomFaulkner** [comment]
I have a fork, that I'll submit a PR from soon. It removes all uses of PySimpleGui.

Some functionality is lost, and there is no GUI. But, it installs and works.

https://github.com/TomFaulkner/inputmodule-rs

**Comment by JohnAZoidberg** [comment]
Porting the GUI to tkinter with @moon-jam in #130
