### ISSUE TITLE
LED Matrix takes frame rates it can't report back

### ISSUE THREAD

**Issue by TomFaulkner** [FrameworkComputer/inputmodule-rs#113]
Issuing a high animation-fps rate, such as 5000 seems to be accepted. However, asking the CLI to report it results in `thread main panicked at attempt to divide by zero` in inputmodule.rs:1013:62

It would probably be good to have the application refuse beyond whatever the maximum fps is, and to handle the report rather than panicking.

I assume this is low priority. I might make a PR for this once I'm back from vacation if no one beats me to it.

**Comment by JohnAZoidberg** [comment]
It's actually a bug in the CLI, if you set it over 1000, it'll tell the firmware to set it to 0. I'll submit a PR.

**Comment by JohnAZoidberg** [comment]
Thanks for battle testing our CLI :D

Please feel free to try the linked PR.

**Comment by TomFaulkner** [comment]
Thanks!
