### ISSUE TITLE
README is wrong regarding panic written to flash

### ISSUE THREAD

**Issue by jannic** [FrameworkComputer/inputmodule-rs#27]
The README says: "Additionally the panic message is written to flash"
Unless I'm missing something, this is not true. It looks like you are using `rp2040-panic-usb-boot`, and that's not writing to flash.

It uses a RAM area usually used as a flash cache. So by disabling the flash cache, the panic handler can be sure that this memory is unused and the panic message can be stored there without overwriting anything that could be useful for debugging.

However, in contrast to flash memory, that RAM area will get erased once the rp2040 gets rebooted.

**Comment by JohnAZoidberg** [comment]
Yes, you're definitely right.
I'm just using your `rp2040-panic-usb-boot` crate with its default behavior.
